# Generated by Django 3.2.4 on 2021-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.TextField(default=1622885292.7614102),
        ),
    ]
