# Generated by Django 3.2.4 on 2021-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_content_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.TextField(default=1623845811.671417),
        ),
    ]
