# Generated by Django 3.2.4 on 2021-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0003_auto_20210605_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.TextField(default=1623060387.901529),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.TextField(default=1623060387.901529),
        ),
    ]
