# Generated by Django 3.2.4 on 2021-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0004_auto_20210607_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='writer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.TextField(default=1623060446.12022),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.TextField(default=1623060446.12022),
        ),
    ]
