# Generated by Django 3.2.4 on 2021-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0008_auto_20210616_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623811226.1931493),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.TextField(default=1623811226.1931493),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.TextField(default=1623811226.1931493),
        ),
    ]
