# Generated by Django 3.2.4 on 2021-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0009_auto_20210616_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623845811.671417),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.TextField(default=1623845811.671417),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.TextField(default=1623845811.671417),
        ),
    ]
